using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace PansiyonYonetimSistemi.API.Migrations
{
    /// <inheritdoc />
    public partial class AddSystemSettingsAndCustomerNotes : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Idempotent: Kolon veya tablo zaten varsa hata vermez
            migrationBuilder.Sql(@"
                ALTER TABLE ""Customers"" ADD COLUMN IF NOT EXISTS ""Notes"" text;

                CREATE TABLE IF NOT EXISTS ""SystemSettings"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Key"" character varying(100) NOT NULL,
                    ""Value"" text NOT NULL,
                    ""Description"" character varying(250) NULL,
                    ""UpdatedAt"" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_SystemSettings_Key"" ON ""SystemSettings"" (""Key"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "SystemSettings");
            migrationBuilder.DropColumn(name: "Notes", table: "Customers");
        }
    }
}
