using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PansiyonYonetimSistemi.API.Data;

#nullable disable

namespace PansiyonYonetimSistemi.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260806120000_AddSystemSettingsAndCustomerNotes")]
    public partial class AddSystemSettingsAndCustomerNotes : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                ALTER TABLE ""Reservations"" ADD COLUMN IF NOT EXISTS ""ReservationName"" character varying(200);
                ALTER TABLE ""Reservations"" ADD COLUMN IF NOT EXISTS ""ReservationGroupId"" character varying(36);
                ALTER TABLE ""Reservations"" ALTER COLUMN ""CustomerId"" DROP NOT NULL;
                ALTER TABLE ""Customers"" ADD COLUMN IF NOT EXISTS ""Notes"" text;

                CREATE TABLE IF NOT EXISTS ""SystemSettings"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Key"" character varying(100) NOT NULL,
                    ""Value"" text NOT NULL,
                    ""Description"" character varying(250) NULL,
                    ""UpdatedAt"" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
                );
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_SystemSettings_Key"" ON ""SystemSettings"" (""Key"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "SystemSettings");
            migrationBuilder.DropColumn(name: "Notes", table: "Customers");
        }
    }
}
